#pragma once

enum XACT_WAVEBANK_BGMS : int
{
    XACT_WAVEBANK_BGMS_BGM_TITLE = 0,
    XACT_WAVEBANK_BGMS_BGM_SELECT = 1,
    XACT_WAVEBANK_BGMS_BGM_PLAY = 2,
    XACT_WAVEBANK_BGMS_BGM_RESULT = 3,
};

#define XACT_WAVEBANK_BGMS_ENTRY_COUNT 4
