#pragma once
#include "NecromaLib/GameData/CommonStruct.h"

enum XACT_WAVEBANK_SES : unsigned int
{
    XACT_WAVEBANK_SES_EARTHMACHINEATTACK = 0,
    XACT_WAVEBANK_SES_FIREMACHINEATTACK = 1,
    XACT_WAVEBANK_SES_WATERMACHINEATTACK = 2,
    XACT_WAVEBANK_SES_WINDEARTHMACHINEATTACK = 3,
};

// ëÆê´ÇWAVEBANK_SESÇ…ïœä∑ÇµÇ‹Ç∑
XACT_WAVEBANK_SES ConvertToElement(ELEMENT element);


#define XACT_WAVEBANK_SES_ENTRY_COUNT 4
