#pragma once

enum XACT_WAVEBANK_SYSTEMSE : int
{
    XACT_WAVEBANK_SYSTEMSE_BUTTOMPUSH = 0,
    XACT_WAVEBANK_SYSTEMSE_BUTTONSELECT = 1,
    XACT_WAVEBANK_SYSTEMSE_POPTEXT = 2,
    XACT_WAVEBANK_SYSTEMSE_MACHINESPAWN = 3,
};

#define XACT_WAVEBANK_SYSTEMSE_ENTRY_COUNT 4
